class CacheException(Exception): ...


class KeyNotFoundError(CacheException): ...


class CacheNotInitializedError(CacheException): ...


class CannotInitCacheTwice(CacheException): ...


class ResponseTypeNotSupported(CacheException): ...
